@echo off
echo Killing all Python processes...
taskkill /F /IM python.exe >nul 2>&1
echo Waiting 3 seconds...
timeout /t 3 /nobreak >nul
echo Starting QNTI system...
python qnti_main.py --port 5003 --debug
pause 